[package]
name = "bifrost-net"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
base64 = "0.23.1"
boringtun = "0.7.1"
etherparse = "0.21.0"
rand_core = { version = "0.6.4", features = ["getrandom"] }
str0m = "0.24.0"
tiny_http = "0.12.0"
toml = "1.1.6"
serde_json = "1"
